# in dev mode you can use "http://insecure.rails-assets.org" see https://rails-assets.org/#/
# NOTE: use "http://", not "https://" for proxy support
source "http://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 3.8.6"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  #gem 'jekyll-manager'
  gem 'html-proofer'
  #gem 'jekyll-plantuml-url-interactive', :git => 'git://github.com/blockspacer/jekyll-plantuml-url-interactive'
  #gem 'jekyll-offline', :git => 'git://github.com/jeremiak/jekyll-offline.git'
  gem 'jekyll-graphviz'
  gem 'jekyll-typogrify'
  gem 'jekyll-picture-tag'
  gem 'jekyll-archives'
  #gem 'jekyll-sitemap', "~> 1.1.1"
  gem 'jekyll-gist'
  #gem 'jekyll-minifier'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?

